### ISSUE TITLE
Strong named

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.AppCenter#11]
I think this package should be strong named.

**Comment by snakefoot** [comment]
Originally strong-name was mostly for NetFramework and the GAC. But I don't think it will hurt to have strong-name, besides having a static AssemblyVersion that confuses some:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i

**Comment by 304NotModified** [comment]
All NLog packages are currently strong named. It's also needed for other policies then the GAC.

Also others do strong name libs (MS, Json.NET etc)

**Comment by snakefoot** [comment]
See also https://github.com/microsoft/appcenter/issues/1321 + https://github.com/microsoft/appcenter-sdk-dotnet/issues/1092 + https://github.com/microsoft/appcenter-sdk-dotnet/issues/1325 (Still pending)

**Comment by 304NotModified** [comment]
it seems it has a strong name nowadays:

https://github.com/microsoft/appcenter/issues/1321#issuecomment-804782144
