### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.AppCenter#4]
I guess we need to setup a CI under the NLog org?

As I see:

![image](https://user-images.githubusercontent.com/5808377/64989116-21e40e00-d8cd-11e9-8160-330cfa06ff33.png)

I tried that: 

(project url: https://ci.appveyor.com/project/nlog/nlog-azureappcenter/)

![image](https://user-images.githubusercontent.com/5808377/64989097-185aa600-d8cd-11e9-980e-6571ba870114.png)

**Comment by snakefoot** [comment]
@304NotModified Yes I have no clue how to setup CI for a project :)

**Comment by 304NotModified** [comment]
Do you like to have access to appveyor or should I look at it?

**Comment by snakefoot** [comment]
Would be very happy if you at some point had some time to look at it  :)

Thought the AppCenter-target was a simple interface, so it would be easy to maintain. And at the same time allow NLog to demonstrate its context-capture ability.

**Comment by 304NotModified** [comment]
Ok!

**Comment by 304NotModified** [comment]
@snakefoot should 1.0 be released on nuget?

**Comment by snakefoot** [comment]
> @304NotModified should 1.0 be released on nuget?

That would be great!

**Comment by 304NotModified** [comment]
It's published :)
