### ISSUE TITLE
AppCenter SDK: Not up to date

### ISSUE THREAD

**Issue by jamers99** [NLog/NLog.AppCenter#8]
There are some new features in the latest AppCenter SDK and so the NLog target should be updated to use those features.
I would like to see the AppCenter NuGet package upgraded to the latest version (2.6.2 as of 12/6).

I'm getting this exception if I manually install the latest AppCenter NuGet package into the same project (turning on LogManager.ThrowExceptions):
![image](https://user-images.githubusercontent.com/20806279/70340274-7c32a200-181e-11ea-826b-514db46e3391.png)

**Comment by snakefoot** [comment]
Strange they are making breaking API-changes without bumping major-version.

**Comment by snakefoot** [comment]
Created https://github.com/microsoft/appcenter-sdk-dotnet/issues/1250 to ask why.

**Comment by snakefoot** [comment]
@jamers99 Possible that you could use AppCenter NuGet package ver. 2.5.0:

https://www.nuget.org/packages/Microsoft.AppCenter/2.5.0

**Comment by snakefoot** [comment]
Pre-Release build available here:

https://ci.appveyor.com/project/nlog/nlog-azureappcenter/builds/29371245/artifacts

**Comment by jamers99** [comment]
@snakefoot thank you for the quick response! Do you have an estimated time when this will be available on NuGet?

**Comment by snakefoot** [comment]
@jamers99 Think it depends on when @304NotModified has time to merge the PR and push to nuget.

**Comment by 304NotModified** [comment]
Working on it :)

**Comment by 304NotModified** [comment]
it's live!

https://www.nuget.org/packages/NLog.Targets.AppCenter/1.1.0
